exports.get_toolbox_modules = function () {
    return [
        {
            name: 'CSV file from sample',
            caption: 'CSV file from sample',
            description: 'CSV file from sample',
            tool_type: 'source',
            icon: null,
            inputs: ['file path'],
            outputs: ['auto1', 'auto2', 'auto3', 'auto4'],
            on_add: 'request_file_sample',
            on_connect_input: null,
            on_connect_output: null,
            editor_type: 'CSVEditor',
            api_endpoint: 'source'
        },
        {
            name: 'CSV file manual configuration',
            caption: 'CSV file manual configuration',
            description: 'CSV file manual configuration',
            tool_type: 'source',
            icon: null,
            inputs: ['file path'],
            outputs: ['field1', 'field2', 'field3', 'field4'],
            on_add: null,
            on_connect_input: null,
            on_connect_output: null,
            editor_type: 'CSVEditor',
            api_endpoint: 'source'
        },
        {
            name: 'Message Queue',
            caption: 'Message Queue',
            description: 'Message Queue',
            tool_type: 'source',
            icon: null,
            inputs: ['queue name'],
            outputs: ['auto1', 'auto2', 'auto3', 'auto4'],
            on_add: null,
            on_connect_input: null,
            on_connect_output: null,
            editor_type: 'QueEditor',
            api_endpoint: 'source'
        },
        {
            name: 'Type Converter',
            caption: 'Type Converter',
            description: 'Type Converter',
            tool_type: 'transform',
            icon: null,
            inputs: ['raw'],
            outputs: ['converted'],
            on_add: null,
            on_connect_input: null,
            on_connect_output: null,
            editor_type: 'TypeConvertEditor',
            api_endpoint: 'mappings'
        },
        {
            name: 'Auto Type Mapping',
            caption: 'Auto Type Mapping',
            description: 'Auto Type Mapping',
            tool_type: 'transform',
            icon: null,
            inputs: ['raw'],
            outputs: ['auto converted'],
            on_add: null,
            on_connect_input: null,
            on_connect_output: null,
            editor_type: 'TypeConvertEditor',
            api_endpoint: 'mappings'
        },
        {
            name: 'Database Table',
            caption: 'Database Table',
            description: 'Database Table',
            tool_type: 'store',
            icon: null,
            inputs: ['field1', 'field2', 'field3', 'field4'],
            outputs: ['DB connection'],
            on_add: 'retrieve_table_definition',
            on_connect_input: null,
            on_connect_output: null,
            editor_type: 'DbTableEditor',
            api_endpoint: 'store'
        },
    ];
}